apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  selector:
    replicas: 1
    matchLabels:
      app: web
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
          - name: site
            image: jpvercosa/conversao-temperatura
            ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: customservice
spec:
  selector:
    app: web #Expõe todos os pods que tem esse Label
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30000
  type: NodePort
